### ISSUE TITLE
Awesome project

### ISSUE THREAD

**Issue by parro-it** [mimecorg/vuido#10]
Hi, [libui-node](https://github.com/parro-it/libui-node/pull/74) author here. 
I'm writing just to say hi and compliment for this awesome project.
Feel free to /CC me if you get problem related to the native part of the project, I'll try to help as I can...

👋🏻

**Comment by mimecorg** [comment]
Hi Andrea! Thank you 🙂. I was just going to reach out to you and say hi as well.

I will definitely need some help with the native part. I have some basic knowledge about Windows API, but I've never done anything related to GTK+ or OS X. I realize that the future of Vuido depends largely on both libui and libui-node, so I'm open for collaboration.

One little thing that immediately comes to my mind is the lack of an insert method for containers. I had to work around this by removing and re-appending all children following the one I need to insert.

Another much higher level problem is that at the moment there's apparently no easy way to package and distribute an application using libui-node for end users. I have a solution for this in my mind, but I have to experiment a bit to see if this is practical.

**Comment by parro-it** [comment]
> Another much higher level problem is that at the moment there's apparently no easy way to package and distribute an application using libui-node for end users. I have a solution for this in my mind, but I have to experiment a bit to see if this is practical.

You may follow these issues about packaging an app: https://github.com/parro-it/libui-node/issues/108 and https://github.com/kusti8/proton-native/issues/43.

Maybe the same tools that are being developed for proton-native could be used by vuido too

> One little thing that immediately comes to my mind is the lack of an insert method for containers. I had to work around this by removing and re-appending all children following the one I need to insert.

There is an issue on libui tracking feature requests for containers: https://github.com/andlabs/libui/issues/328. You may try to ask there first.

Which specific container are you concerned about? Or all of them?

**Comment by mimecorg** [comment]
Yes, proton-native and vuido can definitely reuse the same packaging tools. I saw the solution based on electron-builder, I have to take a closer look at it, but I will have to wait for Windows support.

So far I only implemented the horizontal/vertical box container, but as far as I looked into the docs, they all have this limitation.

**Comment by parro-it** [comment]
> So far I only implemented the horizontal/vertical box container, but as far as I looked into the docs, they all have this limitation.

Yes neither of these have an insertAt method

**Comment by sanriqing** [comment]
！！ This project is really surprising to me. That is great!

**Comment by sotaan** [comment]
Congrats for all the stars, you deserves it!

**Comment by mischnic** [comment]
@konstantinsteinmiller If your looking for a web view component, then not in the near future: https://github.com/andlabs/libui/issues/315.

**Comment by konstantinsteinmiller** [comment]
ahh ok, thats sad. But could be a major enabler for Webdevelopers.

**Comment by uniquejava** [comment]
Wow!!! if it could integrate something like webview.. we would reuse all javascript chart libraries like d3.js, echarts. that would be awesome.

**Comment by sotaan** [comment]
I think this is not related to this project directly. Though it may be interesting to see how weex / nativescript compile components and check if it can be integrated along with vuido
