### ISSUE TITLE
question

### ISSUE THREAD

**Issue by kylepwarren** [mimecorg/vuido#18]
I really like the idea of html/js/etc to desktop app.
I really do NOT like the idea of a desktop app being dependent on listening to tcp/ip ports.

It looks like this one might not be...? is it?   If so, then what's the alternative for getting input/data from the ui to the code[since ajax & not tcp/ip]. 

Are there any like that[besides vuido]?

**Comment by mimecorg** [comment]
I don't understand this question. There is no need to use any TCP/IP ports in order to create a GUI.

**Comment by mischnic** [comment]
I think by "tcp/ip ports" you mean running a local web server and then opening the page in your browser.
If you want to use HTML and Javascript for a desktop app, take a look at [Electron](https://electronjs.org/).
