### ISSUE TITLE
Packaging and naming conventions

### ISSUE THREAD

**Issue by nothingismagick** [mimecorg/vuido#2]
This is a cool little project, and I know it is early in its development, but I wanted to make a recommendation. I sort of followed the instructions and was able to modify and build a vuido node app relatively painlessly - even including the `fs` module to read out the CWD contents.

However, when I tried to run the main.js project from another folder, it complained that it couldn't find `../../dist/vuido.js`.

![screen shot 2018-05-19 at 14 53 57](https://user-images.githubusercontent.com/35242872/40268790-8fab6726-5b74-11e8-965b-0276370eae59.png)

Now, I just cloned the project and worked in the "example folder", so there might be other issues when importing / requiring it, however I find the number of main.js files disconcerting - as are the number of dist folders. Might this moment in time be a good one to think about the packaging?

**Comment by mimecorg** [comment]
The `example/` folder is set up to use the local build of Vuido, not the npm package, so it's configured a bit differently. It's not meant to be a template for a new project. I just use it for testing.

I will create a template for vue-cli that can be used to start a new project.

**Comment by nothingismagick** [comment]
Ok great.
