### ISSUE TITLE
Vue cli 3 support?

### ISSUE THREAD

**Issue by focussing** [mimecorg/vuido#24]
First of all, I think this could be a very good Electron alternative. Especially regarding the distribution packet size. Do you have an idea how it would relate to Electron (percentage wise)?

My question; are there plans for vue cli 3 support? I have completely switched to cli3 now and I think everyone should... :)

**Comment by mimecorg** [comment]
The package size is about 22 MB for Windows 32-bit (see [here](https://github.com/mimecorg/vuido/issues/4#issuecomment-393525375)), the Electron package for the same platform is about 120 MB.

Yes, I'm planning to add support for vue cli 3, but at the moment I'm not sure how hard it will be to integrate with its plugin based architecture.

**Comment by mimecorg** [comment]
Note that you can still use the vuido-webpack-template with vue-cli 3, you just have to install @vue/cli-init. The new plugin based Vue CLI is designed specifically for web application and I don't think it would work well with Vuido.
