### ISSUE TITLE
Vuido.mimec.org is inaccessible

### ISSUE THREAD

**Issue by txs1992** [mimecorg/vuido#25]
Hello, I am a Chinese user and I am open to VPN. I can access your github, but I can't access https://vuido.mimec.org/. I would like to ask if there are other API addresses? Or can I provide a gh-pages?

**Comment by maple3142** [comment]
http://viewdns.info/chinesefirewall/?domain=mimec.org

It seems that `mimec.org` is available in China.

**Comment by txs1992** [comment]
My inaccessible, I can open google,youtube. But can't open vuido.mimec.org

http://viewdns.info/chinesefirewall/?domain=vuido.mimec.org

**Comment by maple3142** [comment]
`vuido.mimec.org` is a subdomain of `mimec.org`, `vuido.mimec.org` works if `mimec.org` works
If you wants to check for `vuido.mimec.org`, you can use: https://www.comparitech.com/privacy-security-tools/blockedinchina/

**Comment by txs1992** [comment]
thanks

**Comment by mimecorg** [comment]
Note that vuido.mimec.org is just an alias for hosting.gitbook.com, so if there are any issues with it, you should report them to [gitbook](https://github.com/GitbookIO/gitbook).
