### ISSUE TITLE
html/custom tags

### ISSUE THREAD

**Issue by wormen** [mimecorg/vuido#27]
how can I use tags to output items, for example, to display a table?

**Comment by mimecorg** [comment]
I'm not sure what you are trying to do, but you cannot use HTML tags in Vuido. The table widget it currently being implemented in libui, so in the future it will be available in Vuido.

**Comment by wormen** [comment]
how to call the table in `libui`?

**Comment by mimecorg** [comment]
As I said, the table is currently being implemented, so it's not available yet.
