### ISSUE TITLE
change name

### ISSUE THREAD

**Issue by vieruu** [mimecorg/vuido#5]
This is an early project so I think changing the name isn't to late

vuido isn't sounding that great, I mean it looks ugly and is scratching my ears when somebody is saying it

I have some ideas for the new name:
- vue-desktop
- vue-native
- vuetron(this is also kinda ugly)

If someone has other ideas let's vote them

**Comment by mimecorg** [comment]
I'm absolutely open for ideas, though Vuido sounds quite good for me 😄. Maybe we pronounce it differently?

I thought about libui-vue for a while, but I didn't want to use a generic name like this, for the same reasons Electron is not called chromium-destkop, for example. Vuetron came to my mind too, but it's already [used](https://github.com/vuetwo/vuetron).
