### ISSUE TITLE
Howto convert an existing web application based on vue

### ISSUE THREAD

**Issue by anh1979** [mimecorg/vuido#50]
Hi,
I am evaluating which tool to use to wrap our existing vue-based web application for Windows MacOS and Linux. I came upon vuido and now I am intrigued to use it, because we already use vue for the frontend in our web application project. But I can't find any documentation or example how to use vuido with an existing vue project...

Can you provide some links / info / examples about this?

Thanks in advance, 
Anne

**Comment by mimecorg** [comment]
The link to the documentation is in the README:

> You can find the full documentation of Vuido at [vuido.mimec.org](https://vuido.mimec.org).

**Comment by anh1979** [comment]
Well, I saw the documentation, but I am not sure how to continue. But thanks anyway.

**Comment by atilacamurca** [comment]
@anh1979 vuido it's a tool to create desktop applications, and beyond just run a desktop app, it uses desktop libraries (see <https://github.com/andlabs/libui#runtime-requirements>).

So, to answer you question, it's not possible to convert your existing web project to vuido. Vuido uses custom tags that are converted to real desktop widgets. You would not be able to, for example, use some third-party libraries, such as bootstrap.

For your use case, you should consider Electron or NW.js.
