### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by Sombian** [mimecorg/vuido#51]
always coming with myriads of errors.
intended?

**Comment by Zifiri** [comment]
I have same problem

**Comment by dalisoft** [comment]
I think it's because of Node.js v11 and/or v12. Same issue with Proton-Native

**Comment by vkensou** [comment]
> I think it's because of Node.js v11 and/or v12. Same issue with Proton-Native

Thank you. I install node.js v10, and it worked!!
