### ISSUE TITLE
Error: TextInput does not have attribute type

### ISSUE THREAD

**Issue by profblackjack** [mimecorg/vuido#53]
When binding a value to the 'type' attribute of a TextInput, and causing an update to change the type, vuido throws an Error

> [Vue warn]: Error in nextTick: "Error: TextInput does not have attribute type"
(node:22840) UnhandledPromiseRejectionWarning: Error: TextInput does not have attribute type

example:
```
<template>
  <Box>
    <TextInput :type="activeType" />
    <Button v-on:click="toggleActiveType" >Change Type</Button>
  </Box>
</template>

<script>
export default {
  data() {
    return { activeType: "password" };
  },
  methods: {
    toggleActiveType () {
      this.activeType = this.activeType === "password" ? "text" : "password";
    }
  }
};
</script>
```

**Comment by mimecorg** [comment]
Unfortunately, the type of the TextInput currently cannot be changed at run-time.

**Comment by profblackjack** [comment]
Darn, I thought that might be the case seeing that the underlying libui control changed based on type, but I crossed my fingers and hoped anyway.

Thanks for confirming!
