### ISSUE TITLE
Only update when the mouse moves in front of the window?

### ISSUE THREAD

**Issue by vinhjaxt** [mimecorg/vuido#55]
Hello contributors,
I have some questions here.
Here is my code:
```js
setInterval(() => {
console.log('Tick tock')
}, 1000)
```
I think it will write on the console every second: tick tock
but no, it will only print when i move the mouse in front of the window :(
Is it right?
However, at some point, I will write:
```js
setTimeout(() => {
// do sth
}, ms)
```
and it was never triggered until I moved the mouse? @@
Please give me an answer. Thank you.

**Comment by vinhjaxt** [comment]
Update:
when i insert:
```js
setInterval(() => {}, 1000)
```
into main.js
everything works ✌️  :V

**Comment by vinhjaxt** [comment]
I think something has blocked the main thread.

**Comment by mimecorg** [comment]
I guess it's a problem with libui-node because it replaces the standard setTimeout and setInterval methods.

**Comment by mischnic** [comment]
> I guess it's a problem with libui-node because it replaces the standard setTimeout and setInterval methods.

(Yes. This issue is the reason why libui-node originially replaced these functions, don't know why it is still happening though.)

**Comment by vinhjaxt** [comment]
Yes, I think so, I will close this issue because it does not belong to Vuido.
Thanks everyone.

**Comment by vinhjaxt** [comment]
```js
const libui = require('libui-node')
libui.startLoop()
setInterval(() => console.log('tick'), 1000)
```
This code solves my problem, thanks again.
