### ISSUE TITLE
Custom ui, design?

### ISSUE THREAD

**Issue by akadlec** [mimecorg/vuido#62]
Just want to ask if in vuido is possible create custom ui? Something like styles in electron or nativescript. I have web app a now i want to transofrm it to the desktop app

**Comment by mimecorg** [comment]
Not much can be done with libui, I would have to rewrite everything using Qt which has pretty good styling support. Unfortunately that would be quite a lot of work and I currently don't have enough resources to work on this.

**Comment by akadlec** [comment]
Hi, thanks for the info
