### ISSUE TITLE
SSL cert issue on https://vuido.mimec.org/

### ISSUE THREAD

**Issue by madhavarshney** [mimecorg/vuido#64]
Seems like this is related to #58 

<img width="788" alt="Screen Shot 2020-06-10 at 1 27 40 AM" src="https://user-images.githubusercontent.com/40002855/84245234-95f8be80-aab9-11ea-8cbd-d847244001b0.png">

**Comment by mischnic** [comment]
It works corrrectly for me

**Comment by madhavarshney** [comment]
Seems to work correctly now. Maybe @mimecorg fixed it? Also, it seems like this is something to do with GitBook.
