### ISSUE TITLE
Documentation site not accessible

### ISSUE THREAD

**Issue by TheJaredWilcurt** [mimecorg/vuido#7]
When I go to the documentation site there is some problem with the HTTPS cert or something and the browser flags it as a dangerous site, I can try to bypass it but my corprate VPN's DNS or something flags it and says it is **"👻*A Malware*👻"**

I think it would make more sense to host the documentation on GitHub pages. You would inherit the https automatically, and it would be located at:

* https://mimecorg.github.io/vuido

To do this, make a new branch called `gh-pages` and add a file called `.no-jekyll`, and then you have a static hosted website for free where people can contribute to the documentation. You could even use VuePress for it if you want, or something else, I don't really care, just throwing out ideas.

**Comment by TheJaredWilcurt** [comment]
Note: I am able to get to the documentation by using a proxy site, but obviously it just doesn't look good to adopters.

**Comment by faraazahmad** [comment]
@TheJaredWilcurt GitBooks is a pretty popular site, you can easily add/update documentation to it. It serves pages through HTTPS by default. Could you please test whether other pages on Gitbooks have the same problem for you?

**Comment by TheJaredWilcurt** [comment]
👍 mimec.org
👍 gitbooks.com
👍 docs.gitbooks.com
❌ vuido.mimec.com

**Comment by faraazahmad** [comment]
https://vuido.mimec.org/

**Comment by mimecorg** [comment]
I have no idea where did the wrong link come from, but yes, the correct address is https://vuido.mimec.org/.
